name: ${project.name}
main: com.michaelelin.standmaster.StandMasterPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: false
authors: [Dumbo52]
api-version: 1.17
commands:
  stand:
    description: StandMaster9000 commands
    aliases: [sm, standmaster, standmaster9000]